name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.8.5

    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        run: |
          apt-get update -qy
          apt-get install -y python3-dev python3-pip
          pip3 install -r requirements.txt
          pip3 install pytest-django pytest factory-boy
      - name: Running tests
        run: pytest ecommerce/
        env:
          DATABASE_URL: sqlite:///ecommerce.sqlite3
